name: CI
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
env:
  CSV_URL: "MLProject/data_train.csv"

permissions:
  contents: write
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
 
      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
 
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
      
      # Run as a mlflow project
      - name: Run mlflow project
        env:
          MLFLOW_ALLOW_FILE_STORE: "true"
          # Alihkan backend tracking menggunakan database SQLite lokal
          MLFLOW_TRACKING_URI: "sqlite:///mlflow.db"
        run: |
          mlflow run file://${{ github.workspace }}/MLProject --env-manager=local --experiment-name "Credit Scoring"
          
      # Save models to GitHub Repository
      # Save models to GitHub Repository
      - name: Save mlruns to repo
        run: |
          # Menggunakan bot bawaan github actions agar pasti berhasil tanpa memerlukan github secrets tambahan
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Tambahkan artifact dan database SQLite
          git add mlruns/ mlflow.db
          
          # Lakukan commit jika ada perubahan data baru
          git commit -m "Save mlruns and database from CI run" || echo "No changes to commit"
          
          # Dorong ke branch utama (main)
          git push origin main
